[project]
name = "promptopt"
version = "0.1.0"
dependencies = [
    "typer"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
